### PR TITLE
Update SidraToken.sol: Enhanced 'for' loops

### PR DESCRIPTION
**Pull request by Aryan9592**
For loops have been enhanced which costs less gas than before.

Refer [this](https://gist.github.com/grGred/9bab8b9bad0cd42fc23d4e31e7347144#for-loops-improvement) for a better explanation
Also got some typos fixed

Thanks!

### CODE REVIEW

**Comment by noumanmhd** [comment]
Thank @Aryan9592  you for your contribution to the project! We really appreciate your effort in enhancing the for loops and fixing those typos.

We're glad to see you actively participating in its development. Please know that you are always welcome to contribute more. Your ideas and contributions can help us make the project even better.

If you have any more improvements or ideas in mind, feel free to submit additional pull requests, or if you have any questions or need assistance with anything, don't hesitate to reach out. We're here to support you.

Once again, thank you for your valuable contribution. Looking forward to more great work from you!

**Comment by nabajiban1** [comment]
Nice big projects sidra family

**Comment by mohdsaniAdo** [comment]
Sidra everywhere

**Comment by Agungoka889** [comment]
Sidra nice proyek

**Comment by Agungoka889** [comment]
Sidra projects for nets future

**Comment by Hkhomeking** [comment]
I thought you said mainnet is this month October. And October ends today.
so how is that possible?

**Comment by Mohdakkd** [comment]
Sidra to the moon. We are expecting a good price 🚀

**Comment by malrlboroman76** [comment]
> Sidra to the moon. We are expecting a good price 🚀

OK, then let's see what happens.

**Pull request merged**
